apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cinder-csi-controllerplugin-rbac.yaml
  - cinder-csi-controllerplugin.yaml
  - cinder-csi-nodeplugin-rbac.yaml
  - cinder-csi-nodeplugin.yaml
  - csi-cinder-driver.yaml
patches:
  - path: lab-controller.yaml
  - path: lab-node.yaml
